SELECT * FROM FLOW_SETTING_MAIN fsm -- 流程設定主表
JOIN FLOW_STAGE_SETTING fss ON fsm.FLOW_ID = fss.FLOW_ID -- 流程角色
JOIN FLOW_ROLES fr ON fr.ROLE_ID = fss.ROLE_ID -- 流程關卡對應設定表
-- 關卡設定檔

-- 上下關聯
-- SIGN_FORM_MAIN.FLOW_ID = FLOW_STAGE_SETTING.FLOW_ID
-- SERVICE_CODE.FLOW_NO = FLOW_SETTING_MAIN.FLOW_NO 

SELECT * FROM SIGN_FORM_MAIN sfm -- 簽核表單主檔
JOIN PAM_SYSTEM_SERVICES pss ON sfm.SERVICE_CODE = pss.SERVICE_CODE -- 系統維護 - 簽核流程樣板維護
JOIN SIGN_STAGE ss ON sfm.SIGN_FORM_ID = ss.SIGN_FORM_ID -- 簽核關卡
-- 設定後的關卡
