//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoSharing.DB_EntitySQL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PhotoSharingEntities : DbContext
    {
        public PhotoSharingEntities()
            : base("name=PhotoSharingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Comments> Comments { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
    
        public virtual int Add_Comment(string username, string subject, string body, Nullable<long> photoid)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var subjectParameter = subject != null ?
                new ObjectParameter("subject", subject) :
                new ObjectParameter("subject", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("body", body) :
                new ObjectParameter("body", typeof(string));
    
            var photoidParameter = photoid.HasValue ?
                new ObjectParameter("photoid", photoid) :
                new ObjectParameter("photoid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Add_Comment", usernameParameter, subjectParameter, bodyParameter, photoidParameter);
        }
    }
}
