//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04Model_EF.Models
{
    using System;
    using System.Collections.Generic;
    //04-2-5 using System.ComponentModel 及 System.ComponentModel.DataAnnotations
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    //04-2-6 在原程式中加入驗證功能標籤 
    public partial class tStudent
    {
        [DisplayName("學號")]
        [Required(ErrorMessage ="學號不可空白")]
        public string fStuId { get; set; }

        [DisplayName("姓名")]
        [Required(ErrorMessage = "姓名不可空白")]
        public string fName { get; set; }

        [DisplayName("信箱")]
        [Required(ErrorMessage = "信箱不可空白")]
        [EmailAddress(ErrorMessage = "信箱格式有誤")]
        public string fEmail { get; set; }

        [DisplayName("成績")]
        [Range(0,100, ErrorMessage = "請填入0~100的整數")]
        public Nullable<int> fScore { get; set; }
    }
}
