//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mxic.ITC.PAM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAM_AF_DISABLED_DETAIL
    {
        public string STATUS { get; set; }
        public Nullable<int> SERVICE_NAME { get; set; }
        public string DISABLED { get; set; }
        public Nullable<System.DateTime> PRECLOSE_DATE { get; set; }
        public decimal ID { get; set; }
        public Nullable<decimal> AF_DISABLED_ID { get; set; }
        public Nullable<decimal> ACCOUNT_ID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual FUNCTION_TYPE FUNCTION_TYPE { get; set; }
        public virtual PAM_AF_DISABLED PAM_AF_DISABLED { get; set; }
    }
}
