//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mxic.ITC.PAM.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAM_PS_DISABLELIST_DETAIL
    {
        public decimal ID { get; set; }
        public string ITEM { get; set; }
        public string FUNCTION_TYPE { get; set; }
        public string USE_TYPE { get; set; }
        public string ASSETID { get; set; }
        public string NAME { get; set; }
        public string SERIAL { get; set; }
        public string MODULE { get; set; }
        public Nullable<decimal> PS_DISABLELIST_ID { get; set; }
        public Nullable<decimal> ACCOUNT_ID { get; set; }
    
        public virtual ACCOUNT ACCOUNT { get; set; }
        public virtual PAM_PS_DISABLELIST PAM_PS_DISABLELIST { get; set; }
    }
}
